name: MCProfiler
main: org.sweetiebelle.mcprofiler.bukkit.MCProfilerPlugin
version: $version
authors: [SweetieBelle, Hepolite]
softdepend: [CommandBook, VanishNoPacket, Vault, SuperVanish, PremiumVanish]
description: >
             Allows the creation of profiles on users. Tracks their IP, and allows creation of notes.
commands:
   MCProfiler:
      description: Core command for MCProfiler. Use /MCProfiler help for info
      usage: /<command> <arguments>
   status:
      description: Short command for /MCProfiler info
      usage: /<command> <playername | uuid>
   note:
      description: Short command for /MCProfiler addnote
      usage: /<command> <playername | uuid> <note>
permissions:
    mcprofiler.help:
      description: Allows usage of /MCProfiler help
    mcprofiler.addnote:
      description: Allows usage of /MCProfiler addnote
    mcprofiler.notifiedofalts:
      description: Allows player to recieve notification of players alts.
    mcprofiler.info.basic:
      description: Allows user to get a name on /MCProfiler info
    mcprofiler.info.basic.uuid:
      description: Allows user to get UUID on /MCProfiler info
    mcprofiler.info.basic.previoususernames:
      description: Allows user to get previous usernames on /MCProfiler info
    mcprofiler.info.online:
      description: Allows user to get Online or last online status on /MCProfiler info
    mcprofiler.info.ip:
      description: Allows user to get IP on /MCProfiler info
    mcprofiler.info.position:
      description: Allows user to get last position on /MCProfiler info
    mcprofiler.uuid:
      description: Allows usage of /MCProfiler uuid
    mcprofiler.listlinks:
      description: Allows usage of /MCProfiler listlinks
    mcprofiler.lookup:
      description: Allows usage of /MCProfiler lookup
    mcprofiler.readnotes:
      description: Allows usage of /MCProfiler readnotes. Allows user to read notes on /MCProfiler info.
    mcprofiler.reload:
      description: Allows usage of /MCProfiler reload
    mcprofiler.listips:
      description: Allows usage of /MCProfiler listips
    mcprofiler.maintenance:
      description: Allows usage of /MCProfiler maintenance
